[project]
name = "mood"
version = "1.0"
description = "Client-Server MOOD"
authors = [
    { name = "Mikhail Nikitin", email = "s02220189@gse.cs.msu.ru" }
]
keywords = ["game", "client-server", "fun", "otl_pls"]
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "setuptools",
    "sphinx",
    "doit",
    "python-cowsay",
    "flake8",
    "pycodestyle",
    "pydocstyle",
    "appscript"
]
[build-system]
requires=["setuptools"]
build-backend = "setuptools.build_meta"

[project.scripts]
client = "mood.client.__main__:start_main"
server = "mood.server.__main__:run_main"

[tool.setuptools]
packages = ["mood.client","mood.server", "mood.common", "mood", "check"]
include-package-data = true
package-dir = {"mood" = "mood"}

[tool.setuptools.package-data]
"mood" = ["**"]
"documentations" = ["*.html"]




