[project]
name = "mood"
version = "1.0"
description = "Client-Server MOOD"
authors = [
    { name = "Mikhail Nikitin", email = "s02220189@gse.cs.msu.ru" }
]
keywords = ["game", "client-server", "fun", "otl_pls"]
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "setuptools",
    "sphinx",
    "doit",
    "python-cowsay",
    "flake8",
    "pycodestyle",
    "pydocstyle"
]
[build-system]
requires=["setuptools", "Sphinx", "build", "doit", "python-cowsay"]
build-backend = "setuptools.build_meta"

[project.scripts]
client = "mood.client.__main__:client"
server = "mood.server.__main__:server"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-dir]
mood = "mood"

[tool.setuptools.package-data]
mood = ["mood/server/*/*/*/*.mo", "mood/docs/*"]


